#!/bin/bash

GIT_PATH=$(cat /opt/dmenuXgit/dmenuXgit.conf)

echo "$GIT_PATH"

if [[ "$GIT_PATH" == "" ]]
then
	# Pass directory
	ERR=$(echo "" | dmenu -i -p "No GitHub path found. Please run the setup file.")
	exit	
fi

OP=$(cat /opt/dmenuXgit/dmenuXgit.conf | rev | cut -d "/" -f1 | rev | awk '{print newl, $1; newl="\\n"}' )
CM=$(echo -e $OP | dmenu -i -p "Choose repository ")
GIT_PATH=$(grep $CM /opt/dmenuXgit/dmenuXgit.conf)

terminal -cd "$GIT_PATH" -e /opt/dmenuXgit/script.sh
