#!/bin/bash

GIT_PATH=$(cat /usr/share/dmenuxgit/dmenuxgit.conf)

if [[ "$GIT_PATH" == "" ]]
then
	# Pass directory
	CHS=$(echo "" | dmenu -i -p "Enter the absolut path to you local git project:")
	echo "$CHS" >> /usr/share/dmenuxgit/dmenuxgit.conf
fi

# -g /path/to/git/project 
while getopts g: flag
do
	echo ${OPTARG} >> /usr/share/dmenuxgit/dmenuxgit.conf
done

# Choose one of the Git-Repositories from /usr/share/dmenuxgit/dmenuXgit.conf
OP=$(cat /usr/share/dmenuxgit/dmenuxgit.conf | sed -e "s,/\+$,," -e "s,^/\+,," | rev | cut -d "/" -f1 | rev | awk '{print newl, $1; newl="\\n"}' )
CM=$(echo -e $OP | dmenu -i -p "Choose repository ")
GIT_PATH=$(grep $CM /usr/share/dmenuxgit/dmenuxgit.conf)

terminal -cd "$GIT_PATH" -e /usr/share/dmenuxgit/dxgscript.sh