#!/bin/bash

GIT_PATH=$(cat /opt/dmenuXgit/dmenuXgit.conf)

echo "$GIT_PATH"

if [[ "$GIT_PATH" == "" ]]
then
	# Pass directory
	ERR=$(echo "" | dmenu -i -p "No GitHub path found. Please run the setup file.")
	exit	
fi

terminal -cd "$GIT_PATH" -e /opt/dmenuXgit/script.sh
