#!/bin/bash

GIT_PATH=$(cat /home/"$USER"/dmenuXgit/dmenuXgit.conf)

echo "$GIT_PATH"

if [[ "$GIT_PATH" == "" ]]
then
	# Pass directory
	ERR=$(echo "" | dmenu -i -p "No GitHub path found. Please run the setup file.")
	exit	
fi

branch() {
	if [[ $1 == "add" ]]
	then
		add_process

	elif [[ $1 == "commit" ]]
	then
		commit_process

	elif [[ $1 == "pull" ]]
	then 
		pull_process

	elif [[ $1 == "pull" ]]
	then
		push_process

	elif [[ $1 == "status" ]]
	then
		status_process
	fi
}

add_process() {
	echo "TODO"
}

commit_process() {
	OPT=""
	MSG=$(echo $OPT | dmenu -i -p "Write commit message:")
	git commit $MSG
	
	OPT="add\ncommit\npush\nstatus\nexit"
	CM=$(echo -e $OPT | dmenu -i -p "git ")
	branch $CM
}

pull_process() {
	git pull

	OPT="add\ncommit\npush\nstatus\nexit"
	CM=$(echo -e $OPT | dmenu -i -p "git ")
	branch $CM
}

push_process() {
	git push

	OPT="add\ncommit\npull\nstatus\nexit"
	CM=$(echo -e $OPT | dmenu -i -p "git ")
	branch $CM
}

status_process() {
	git status

	OPT="add\ncommit\npull\npush\nstatus\nexit"
	CM=$(echo -e $OPT | dmenu -i -p "git ")
	branch $CM
}


terminal -cd "$GIT_PATH" 

OPT="add\ncommit\npull\npush\nstatus"

CM=$(echo -e $OPT | dmenu -i -p "git ")

branch $CM
