#!/bin/bash

branch() {
	if [[ $1 == "add" ]]
	then
		add_process

	elif [[ $1 == "commit" ]]
	then
		commit_process

	elif [[ $1 == "pull" ]]
	then 
		pull_process

	elif [[ $1 == "push" ]]
	then
		push_process

	elif [[ $1 == "status" ]]
	then
		status_process
	fi
}

add_process() {
	git status > untracked_files.txt
	GREP=$(grep 'nothing to commit, working tree clean' untracked_files.txt)
	if [[ "$GREP" != "" ]]
	then
		echo "Nothing to commit"
	else
		echo "Something to commit"
	fi

	rm untracked_files.txt
}

commit_process() {
	OPT=""
	MSG=$(echo $OPT | dmenu -i -p "Write commit message:")
	git commit -m "$MSG"
	
	OPT="add\ncommit\npush\nstatus\nexit"
	CM=$(echo -e $OPT | dmenu -i -p "git ")
	branch $CM
}

pull_process() {
	git pull

	OPT="add\ncommit\npush\nstatus\nexit"
	CM=$(echo -e $OPT | dmenu -i -p "git ")
	branch $CM
}

push_process() {
	git push

	OPT="add\ncommit\npull\nstatus\nexit"
	CM=$(echo -e $OPT | dmenu -i -p "git ")
	branch $CM
}

status_process() {
	git status

	OPT="add\ncommit\npull\npush\nstatus\nexit"
	CM=$(echo -e $OPT | dmenu -i -p "git ")
	branch $CM
}

OPT="add\ncommit\npull\npush\nstatus"

CM=$(echo -e $OPT | dmenu -i -p "git ")

branch $CM
